server {
    listen 10801;
    server_name localhost;

    # 根目录指向Nginx托管的静态文件
    root /usr/share/nginx/html;
    index index.html index.htm;

    # 解决React路由刷新404问题
    location / {
        try_files $uri $uri/ /index.html;
    }

   

    # 静态资源缓存（可选）
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }
}